### ISSUE TITLE
这个框架可以热更新吗？

### ISSUE THREAD

**Issue by yeph** [zhitaocai/CocosCreator-GG-Framework#1]
这个框架的热更新大佬能说一下吗？

**Comment by zhitaocai** [comment]
并没有直接支持，论坛有很多 2.4.x 版本的热更方案，你可以参考下

* https://forum.cocos.org/t/topic/102147
* https://forum.cocos.org/t/topic/101219
* https://forum.cocos.org/t/assetbundle/98711

**Comment by yeph** [comment]
好的
