### ISSUE TITLE
AB包有嵌套，打包有问题。

### ISSUE THREAD

**Issue by SungKT** [zhitaocai/CocosCreator-GG-Framework#2]
AB加载顺序commonbundle>gamebundle，
BootPanelPrefab（_commonbundle_）脚本使用了GameSettingModule（_gameBundle_，该模块还未加载），
打包web平台复现。

**Comment by zhitaocai** [comment]
可能是旧版本问题，框架还在更新开发中，每周一到周五晚上会更新
拉新版本的框架下来应该解决了的

@see https://github.com/zhitaocai/CocosCreator-GG-Framework/blob/master/assets/commonbundle/scripts/boot/BootPanelPrefab.ts#L42

**Comment by zhitaocai** [comment]
已修复
